name: special-garbanzo

channels:
  - ranaroussi
  - conda-forge
  - defaults

dependencies:
  - black
  - bs4
  - click
  - mamba
  - pandas
  - dtale
  - html5lib
  - lxml
  - pip
  - plotly
  - python=3.9
  - requests
  - selenium
  - yfinance
  - pip:
    - robin-stocks
